import { createFileRoute, Link } from '@tanstack/react-router'
import { Check, X, Zap, Star, ArrowRight } from 'lucide-react'
import { Navbar } from '../components/Navbar'
import { Footer } from '../components/Footer'

function PricingPage() {
  const plans = [
    {
      name: 'Free',
      price: '£0',
      period: 'forever',
      description: 'Perfect for individuals just getting started with AI content',
      gradient: '',
      highlighted: false,
      features: [
        { text: '10 AI generations per day', included: true },
        { text: '3 AI Tools (Blog, Email, Social)', included: true },
        { text: 'Standard generation speed', included: true },
        { text: 'Copy & export content', included: true },
        { text: 'Community support', included: true },
        { text: 'All 8 AI Tools', included: false },
        { text: 'Unlimited generations', included: false },
        { text: 'Priority support', included: false },
        { text: 'API access', included: false },
        { text: 'Team workspace', included: false },
      ],
      cta: 'Start Free',
      ctaLink: '/tools' as const,
    },
    {
      name: 'Pro',
      price: '£29',
      period: '/month',
      annualPrice: '£23',
      description: 'For creators, marketers, and small businesses serious about content',
      gradient: 'from-violet-600/20 to-indigo-600/10',
      highlighted: true,
      features: [
        { text: 'Unlimited AI generations', included: true },
        { text: 'All 8 AI Tools', included: true },
        { text: 'Priority generation speed', included: true },
        { text: 'Copy, export & download', included: true },
        { text: 'Email & chat support', included: true },
        { text: 'Custom tone profiles', included: true },
        { text: 'Generation history', included: true },
        { text: 'API access', included: false },
        { text: 'Team workspace', included: false },
        { text: 'White-label exports', included: false },
      ],
      cta: 'Start 7-Day Free Trial',
      ctaLink: '/tools' as const,
    },
    {
      name: 'Business',
      price: '£79',
      period: '/month',
      annualPrice: '£63',
      description: 'For agencies and teams producing content at scale',
      gradient: '',
      highlighted: false,
      features: [
        { text: 'Everything in Pro', included: true },
        { text: 'Team workspace (up to 10)', included: true },
        { text: 'Brand voice profiles', included: true },
        { text: 'API access', included: true },
        { text: 'Priority support + onboarding', included: true },
        { text: 'White-label exports', included: true },
        { text: 'Custom integrations', included: true },
        { text: 'Advanced analytics', included: true },
        { text: 'Dedicated account manager', included: true },
        { text: 'Custom AI model tuning', included: true },
      ],
      cta: 'Start Business Trial',
      ctaLink: '/tools' as const,
    },
  ]

  const faqs = [
    {
      q: 'Can I cancel anytime?',
      a: 'Yes, absolutely. Cancel your subscription anytime with one click. No questions asked, no hidden fees.',
    },
    {
      q: 'Do you offer a free trial?',
      a: 'Yes! Pro and Business plans come with a 7-day free trial. No credit card required to start.',
    },
    {
      q: 'What AI model powers NexusAI?',
      a: 'NexusAI is powered by Claude, one of the most capable AI models available. Your content is generated by the same AI used by leading enterprises.',
    },
    {
      q: 'Is my content private?',
      a: 'Absolutely. We never train our AI on your content. Everything you generate is private, owned by you, and never shared.',
    },
    {
      q: 'What counts as a "generation"?',
      a: 'One generation = one piece of content from any tool. Blog post, email, social post — each counts as one generation on the free plan.',
    },
    {
      q: 'Can I switch plans?',
      a: 'Yes. Upgrade or downgrade your plan anytime. When upgrading, you get access immediately. Downgrades take effect at the end of your billing period.',
    },
  ]

  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <Navbar />

      {/* Header */}
      <section className="pt-28 pb-16 px-4 relative overflow-hidden">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-20 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-violet-600/10 rounded-full blur-3xl" />
        </div>
        <div className="relative max-w-3xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400 text-sm font-medium mb-6">
            <Zap className="w-3.5 h-3.5" />
            Simple Pricing
          </div>
          <h1 className="text-5xl font-bold text-white mb-4">
            Invest in your content.
            <br />
            <span className="bg-gradient-to-r from-violet-400 to-indigo-400 bg-clip-text text-transparent">
              Get 10x the output.
            </span>
          </h1>
          <p className="text-gray-400 text-lg mb-6">
            Start free. Upgrade when you're ready. Cancel anytime.
          </p>
          <p className="text-sm text-gray-500">
            💰 Save 20% with annual billing • No credit card required for free trial
          </p>
        </div>
      </section>

      {/* Plans */}
      <section className="pb-24 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="grid md:grid-cols-3 gap-6">
            {plans.map(({ name, price, period, annualPrice, description, gradient, highlighted, features, cta, ctaLink }) => (
              <div
                key={name}
                className={`relative p-8 rounded-3xl border transition-all ${
                  highlighted
                    ? `bg-gradient-to-b ${gradient} border-violet-500/40 shadow-2xl shadow-violet-900/30`
                    : 'bg-white/[0.03] border-white/[0.06]'
                }`}
              >
                {highlighted && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2 flex items-center gap-1.5 px-4 py-1.5 rounded-full bg-gradient-to-r from-violet-600 to-indigo-600 text-white text-sm font-semibold shadow-lg">
                    <Star className="w-3.5 h-3.5 fill-white" />
                    Most Popular
                  </div>
                )}

                <div className="mb-8">
                  <h3 className="text-white font-bold text-xl mb-1">{name}</h3>
                  <p className="text-gray-500 text-sm mb-6">{description}</p>
                  <div className="flex items-end gap-2">
                    <span className="text-5xl font-extrabold text-white">{price}</span>
                    <div className="mb-1">
                      <div className="text-gray-400 text-sm">{period}</div>
                      {annualPrice && (
                        <div className="text-violet-400 text-xs">{annualPrice}/mo billed annually</div>
                      )}
                    </div>
                  </div>
                </div>

                <Link
                  to={ctaLink}
                  className={`block w-full text-center py-3.5 rounded-xl font-semibold transition-all mb-8 ${
                    highlighted
                      ? 'bg-gradient-to-r from-violet-600 to-indigo-600 text-white hover:opacity-90 shadow-lg shadow-violet-900/30'
                      : 'bg-white/[0.07] border border-white/10 text-white hover:bg-white/[0.12]'
                  }`}
                >
                  {cta}
                </Link>

                <ul className="space-y-3.5">
                  {features.map(({ text, included }) => (
                    <li key={text} className="flex items-start gap-3">
                      {included ? (
                        <Check className={`w-5 h-5 flex-shrink-0 mt-0.5 ${highlighted ? 'text-violet-400' : 'text-emerald-400'}`} />
                      ) : (
                        <X className="w-5 h-5 flex-shrink-0 mt-0.5 text-gray-700" />
                      )}
                      <span className={`text-sm ${included ? 'text-gray-300' : 'text-gray-600'}`}>
                        {text}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Trust signals */}
      <section className="py-16 px-4 border-y border-white/[0.06] bg-white/[0.01]">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {[
              { value: '50,000+', label: 'Happy customers' },
              { value: '£0', label: 'Setup fees' },
              { value: '4.9/5', label: 'Average rating' },
              { value: '7-day', label: 'Free trial' },
            ].map(({ value, label }) => (
              <div key={label}>
                <div className="text-3xl font-bold text-white mb-1">{value}</div>
                <div className="text-gray-500 text-sm">{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-24 px-4">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-white mb-3">
              Frequently asked questions
            </h2>
            <p className="text-gray-400">Everything you need to know about NexusAI pricing</p>
          </div>

          <div className="space-y-4">
            {faqs.map(({ q, a }) => (
              <div key={q} className="p-6 rounded-2xl bg-white/[0.03] border border-white/[0.06]">
                <h3 className="text-white font-semibold mb-2">{q}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-16 px-4 border-t border-white/[0.06]">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-white mb-4">
            Ready to 10x your content?
          </h2>
          <p className="text-gray-400 mb-8">
            Start for free today. No credit card required.
          </p>
          <Link
            to="/tools"
            className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-600 text-white font-semibold text-lg hover:opacity-90 transition-all shadow-lg shadow-violet-900/40"
          >
            Start Creating Free
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      <Footer />
    </div>
  )
}

export const Route = createFileRoute('/pricing')({
  component: PricingPage,
})
